<?php

/**
 * @file
 * Contains tpo.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tpo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the tpo module.
    case 'help.page.tpo':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Defines common functionality for all TPO modules.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function tpo_theme() {
  return [
    'tpo' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function tpo_page_attachments(array &$attachments) {
  if ( !(\Drupal::currentUser()->isAnonymous()) ) {
    $attachments['#attached']['library'][] = 'tpo/tpo-toolbar-icon';
  }
}
