<?php
/**
 * @file
 * Install, update and uninstall functions for the profilename install profile.
 */
use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function tpo_paragraph_install() {
  // Can add code in here to make nodes, terms, etc.
  \Drupal::logger('tpo_paragraph')->notice('installed paragraphs modules');

}
